last_change = 2026-09-24T17:35:57.057744Z
addr = 0xfe800
size = 0x35a
name = "SC_DumpWorld_CommandHandler"
type = "long long"

[header]
name = "SC_DumpWorld_CommandHandler"
addr = 0xfe800
type = "long long"

[header.args]
